### PR TITLE
test: add test for poller panic in #271

### LINKED ISSUE #271: Poller panics when it specifies an exporter that does not exist
Version: v21.05.2 ce091de8f

Reproduce with:

```
cat issue_263.yml

Exporters:
  prometheus:
    exporter: Prometheus
    addr: 0.0.0.0
    port: 12990

Pollers:
  unix11:
    datacenter: local
    collectors:
      - Unix
    exporters:
      - missing
```

```
bin/poller --poller unix1 --loglevel 2 --config issue_263.yml

1:53PM ERR command-line-arguments/poller.go:788 > Poller panicked error="goroutine panic => goroutine 1 [running]:\nruntime/debug.Stack(0xc0001acc60, 0x1545703, 0x0)\n\truntime/debug/stack.go:24 +0x9f\nmain.main.func1()\n\tcommand-line-arguments/poller.go:788 +0x96\npanic(0x1545780, 0x1927a80)\n\truntime/panic.go:965 +0x1b9\ngoharvest2/pkg/tree/node.(*Node).GetChildS(0x0, 0x15c700e, 0x8, 0x0)\n\tgoharvest2/pkg/tree/node/node.go:115 +0x26\ngoharvest2/pkg/tree/node.(*Node).GetChildContentS(...)\n\tgoharvest2/pkg/tree/node/node.go:198\ngoharvest2/pkg/conf.GetUniqueExporters(0xc0000a77a0, 0x7ffeefbff5b2, 0xd, 0xc00006c6c0, 0x0, 0xc000100000, 0x0, 0xc0001f1740)\n\tgoharvest2/pkg/conf/conf.go:340 +0x1e8\ngoharvest2/cmd/poller/collector.(*AbstractCollector).WantedExporters(0xc0000ca000, 0x7ffeefbff5b2, 0xd, 0x0, 0x0, 0x0)\n\tgoharvest2/cmd/poller/collector/collector.go:464 +0x4d\nmain.(*Poller).loadCollector(0xc0001e8700, 0xc0001a70a8, 0x6, 0xc000022370, 0x7, 0x1, 0x68)\n\tcommand-line-arguments/poller.go:557 +0xbcb\nmain.(*Poller).Init(0xc0001e8700, 0xc0001e8700, 0x0)\n\tcommand-line-arguments/poller.go:249 +0xb65\nmain.startPoller(0x1930a60, 0xc0001aca80, 0x0, 0x6)\n\tcommand-line-arguments/poller.go:749 +0x4f\ngithub.com/spf13/cobra.(*Command).execute(0x1930a60, 0xc0001ae010, 0x6, 0x6, 0x1930a60, 0xc0001ae010)\n\tgithub.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2\ngithub.com/spf13/cobra.(*Command).ExecuteC(0x1930a60, 0x10014b0, 0x0, 0x0)\n\tgithub.com/spf13/cobra@v1.1.3/command.go:960 +0x375\ngithub.com/spf13/cobra.(*Command).Execute(...)\n\tgithub.com/spf13/cobra@v1.1.3/command.go:897\nmain.main()\n\tcommand-line-arguments/poller.go:795 +0x53\n" Poller=unix11 stack=[{"func":"New","line":"35","source":"errors.go"},{"func":"main.func1","line":"788","source":"poller.go"},{"func":"gopanic","line":"965","source":"panic.go"},{"func":"panicmem","line":"212","source":"panic.go"},{"func":"sigpanic","line":"734","source":"signal_unix.go"},{"func":"(*Node).GetChildS","line":"115","source":"node.go"},{"func":"(*Node).GetChildContentS","line":"198","source":"node.go"},{"func":"GetUniqueExporters","line":"340","source":"conf.go"},{"func":"(*AbstractCollector).WantedExporters","line":"464","source":"collector.go"},{"func":"(*Poller).loadCollector","line":"557","source":"poller.go"},{"func":"(*Poller).Init","line":"249","source":"poller.go"},{"func":"startPoller","line":"749","source":"poller.go"},{"func":"(*Command).execute","line":"856","source":"command.go"},{"func":"(*Command).ExecuteC","line":"960","source":"command.go"},{"func":"(*Command).Execute","line":"897","source":"command.go"},{"func":"main","line":"795","source":"poller.go"},{"func":"main","line":"225","source":"proc.go"},{"func":"goexit","line":"1371","source":"asm_amd64.s"}]
```

### PR DESCRIPTION
**Pull request by cgrinds**
Fixes #271

### CODE REVIEW

File: pkg/conf/conf_test.go [hunk 1]
```diff
@@ -181,3 +181,18 @@ func TestFlowStyle(t *testing.T) {
 		}
 	})
 }
+
+func TestIssue271_PollerPanicsWhenExportDoesNotExist(t *testing.T) {
+	path := "../../cmd/tools/doctor/testdata/testConfig.yml"
+	node, _ := LoadConfig(path)
+	poller := node.GetChildS("Pollers").GetChildS("issue-271")
```
Comment (Hardikl) [inline pkg/conf/conf_test.go:188]: As going forward replacing node to struct, we would be using LoadHarvestConfig with poller, err := GetPoller2(path, "issue-271")

File: pkg/conf/conf_test.go [hunk 2]
```diff
@@ -181,3 +181,18 @@ func TestFlowStyle(t *testing.T) {
...
+	t.Run("Poller panics when exporter does not exist", func(t *testing.T) {
+		exporters, err := GetUniqueExporters(poller, path)
```
Comment (Hardikl) [inline pkg/conf/conf_test.go:190]: I see GetUniqueExporters hasn't been in new form ...

**Review by Hardikl — APPROVED** [review]
