### PR TITLE
fix: port in generate docker command should work for standlone harvest container deployment

### LINKED ISSUE #1703: --port in generate docker command should work for standlone harvest container deployment
image

### PR DESCRIPTION
**Pull request by rahulguptajss**
Fixes #1703

### CODE REVIEW

File: cmd/tools/generate/generate.go [hunk 1]
```diff
@@ -400,7 +400,7 @@ func init() {
 	dFlags.StringVar(&opts.certDir, "certdir", "./cert", "Harvest certificate dir path")
 	dFlags.StringVarP(&opts.outputPath, "output", "o", "", "Output file path. ")
 
-	fFlags.BoolVarP(&opts.showPorts, "port", "p", false, "Expose poller ports to host machine")
+	dFlags.BoolVarP(&opts.showPorts, "port", "p", false, "Expose poller ports to host machine")
```
Comment (Hardikl) [inline cmd/tools/generate/generate.go:403]: do we need `port` in full as well?

**Review by Hardikl — APPROVED** [review]

**Review by cgrinds — APPROVED** [review]
