### PR TITLE
fix: HARVEST_CONF should be consulted when loading files from conf

### LINKED ISSUE #368: HARVEST_CONF not used when looking for collectors
**Describe the bug**
When running poller from a random directory while `HARVEST_CONF` is set correcty finds main `harvest.yml` config file, but fails to find dependent configurations like collectors 👍 
```
nabox-harvest2        | 12:44PM INF command-line-arguments/poller.go:153 > log level used: info Poller=cluster1
nabox-harvest2        | 12:44PM INF command-line-arguments/poller.go:154 > options config: /conf/harvest.yml Poller=cluster1
nabox-harvest2        | 12:44PM INF command-line-arguments/poller.go:179 > started in foreground [pid=24] Poller=cluster1
nabox-harvest2        | 12:44PM ERR command-line-arguments/poller.go:250 > load collector (Zapi): error="open conf/zapi/default.yaml: no such file or directory" Poller=cluster1
nabox-harvest2        | 12:44PM ERR command-line-arguments/poller.go:250 > load collector (ZapiPerf): error="open conf/zapiperf/default.yaml: no such file or directory" Poller=cluster1
nabox-harvest2        | 12:44PM WRN command-line-arguments/poller.go:257 > no collectors initialized, stopping Poller=cluster1
nabox-harvest2        | 12:44PM INF command-line-arguments/poller.go:421 > cleaning up and stopping [pid=24] Poller=cluster1
```

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Harvest version: harvest version 21.05.4-2 (commit 19f8f25) (build date 2021-07-22T15:42:14+0000) linux/amd64
- Command line arguments used: `/netapp-harvest/bin/poller -p cluster1`
- OS: Debian 10.18 container base image
- Install method: native
- ONTAP Version: 9.7
- Other:

**To Reproduce**
- Install Harvest in `/somewhere`
- Move to a different directory
- `export HARVEST_CONF=/somewhere`
- run harvest

**Expected behavior**
Harvest should start and find collectors

**Actual behavior**
```
error="open conf/zapi/default.yaml: no such file or directory"
```

**Possible solution, workaround, fix**
Add `HARVEST_CONF` to search path when looking for additional yaml files

### PR DESCRIPTION
**Pull request by cgrinds**
directory.

Fixes #368

This change addresses the problem when using `bin/poller` but does not work with `bin/harvest`.

The issue with `bin/harvest` is the `os.Exec`-ed executables are not found without more directory work.

The workaround is `cd` into the installation directory before executing `bin/harvest`

### CODE REVIEW

**Comment by ybizeul** [comment]
I also found out the `grafana` has the same problem, not use `HARVEST_CONF`, should it be fixed in the same merge ?

File: cmd/poller/options/options.go [hunk 1]
```diff
@@ -65,6 +65,13 @@ func SetPathsAndHostname(args *Options) {
 	}
 
 	args.HomePath = conf.GetHarvestHomePath()
+	configPath := os.Getenv("HARVEST_CONF")
+	if configPath != "" {
+		if !strings.HasSuffix(configPath, "/") {
+			configPath += "/"
+		}
+		args.HomePath = configPath
+	}
```
Comment (Hardikl) [inline cmd/poller/options/options.go:74]: can we move this logic to conf.go file in GetHarvestHomePath function ?

Comment (cgrinds) [reply cmd/poller/options/options.go:74]: i considered that initially, but was concerned about how frequently that method is called. After profiling it though, it's fine since most of these happen via initialization. I like it, thanks! I'll move this to `GetHarvestHomePath`

Also fixed the `grafana` problem Yann mentioned with this PR

Comment (Hardikl) [reply cmd/poller/options/options.go:74]: As it's moved to conf.go, remove this from here as well.

**Review by Hardikl — APPROVED** [review]

File: cmd/poller/options/options.go (hunk 1 above)
Comment (cgrinds) [reply cmd/poller/options/options.go]: oh dear :) good catch
