### PR TITLE
fix issue when label is treated as a metric

### LINKED ISSUE #66: Status label on cluster_status metric disappears
**Describe the bug**
Status label on `cluster_status` metric disappears roughly after 15mins of starting Harvest

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Harvest version: `harvest version 21.05.1-1 (commit 2211c00) (build date 2021-05-21T01:28:12+0530) linux/amd64`
- Command line arguments used: [e.g. `bin/harvest start --config=foo.yml --collectors Zapi`]
- OS: RHEL 7.9
- Install method: yum
- ONTAP Version: 9.7
- Other:

**To Reproduce**
curl -s localhost:12990/metrics | grep cluster_status

**Expected behavior**
Should report cluster_status metric as 
`cluster_status{cluster="clustername",datacenter="dc",status="ok"} 1`

**Actual behavior**
Initially reports correct metric then after 15minutes roughly the metric turns into
`cluster_status{cluster="clustername",datacenter="dc"} 1`

**Possible solution, workaround, fix**
None

### PR DESCRIPTION
**Pull request by vgratian**
fix #66 

label disappears because the collector tries to store an incoming label value as a numeric metric (since both have the same name, e.g. "status" in the case reported).

currently a workaround, leaving a better solution for the future.

### CODE REVIEW

File: cmd/collectors/zapi/collector/zapi.go [hunk 1]
```diff
@@ -269,28 +271,28 @@ func (me *Zapi) PollData() (*matrix.Matrix, error) {
...
+				logger.Trace(me.Prefix, "%slabel (%s) [%s] set value (%s)%s", color.Yellow, key, label, value, color.End)
+				count += 1
+			} else if metric := me.Matrix.GetMetric(key); metric != nil {
 				if err := metric.SetValueString(instance, value); err != nil {
-					//logger.Warn(me.Prefix, "%sskipped metric (%s) set value (%s): %v%s", color.Red, key, value, err, color.End)
+					logger.Error(me.Prefix, "%smetric (%s) set value (%s): %v%s", color.Red, key, value, err, color.End)
 					skipped += 1
 				} else {
-					//logger.Trace(me.Prefix, "%smetric (%s) set value (%s)%s", color.Green, key, value, color.End)
+					logger.Trace(me.Prefix, "%smetric (%s) set value (%s)%s", color.Green, key, value, color.End)
```
Comment (cgrinds) [inline cmd/collectors/zapi/collector/zapi.go:287]: this was commented out before - did you mean to leave it uncommented?

File: cmd/collectors/zapi/collector/zapi.go [hunk 2]
```diff
@@ -269,28 +271,28 @@ func (me *Zapi) PollData() (*matrix.Matrix, error) {
...
-				instance.SetLabel(label, value)
-				//logger.Trace(me.Prefix, "%slabel (%s) [%s] set value (%s)%s", color.Yellow, key, label, value, color.End)
-				count += 1
 			} else {
 				logger.Debug(me.Prefix, "%sskipped (%s) with value (%s): not in metric or label cache%s", color.Blue, key, value, color.End)
 				skipped += 1
 			}
 		} else {
-			//logger.Trace(me.Prefix, "%sskippped (%s) with no value%s", color.Cyan, key, color.End)
+			logger.Trace(me.Prefix, "%sskippped (%s) with no value%s", color.Cyan, key, color.End)
```
Comment (cgrinds) [inline cmd/collectors/zapi/collector/zapi.go:295]: this was commented out before - did you mean to leave it uncommented?

File: cmd/collectors/zapi/collector/zapi.go [hunk 3]
```diff
@@ -269,28 +271,28 @@ func (me *Zapi) PollData() (*matrix.Matrix, error) {
...
-		logger.Debug(me.Prefix, " > %s(%s)%s <%s%d%s> name=[%s%s%s%s] value=[%s%s%s]", color.Grey, newpath, color.End, color.Red, len(node.GetChildren()), color.End, color.Bold, color.Cyan, node.GetNameS(), color.End, color.Yellow, node.GetContentS(), color.End)
+		key := strings.Join(newpath, ".")
+		logger.Debug(me.Prefix, " > %s(%s)%s <%s%d%s> name=[%s%s%s%s] value=[%s%s%s]", color.Grey, key, color.End, color.Red, len(node.GetChildren()), color.End, color.Bold, color.Cyan, node.GetNameS(), color.End, color.Yellow, node.GetContentS(), color.End)
 
 		if value := node.GetContentS(); value != "" {
-			key := strings.Join(newpath, ".")
-			if metric := me.Matrix.GetMetric(key); metric != nil {
+			if label, has := me.instanceLabelPaths[key]; has {
+				instance.SetLabel(label, value)
+				logger.Trace(me.Prefix, "%slabel (%s) [%s] set value (%s)%s", color.Yellow, key, label, value, color.End)
```
Comment (cgrinds) [inline cmd/collectors/zapi/collector/zapi.go:280]: did you mean to leave this uncommented

**Comment by cgrinds** [comment]
Can you add a unit test that demonstrates the problem and shows this fixes it? Especially since we plan on revisiting this

**Review by cgrinds — COMMENTED** [review]
Can you add a unit test that demonstrates the problem and shows this fixes it? Especially since we plan on revisiting this

File: cmd/collectors/zapi/collector/zapi.go (hunk 3 above)
Comment (vgratian) [reply cmd/collectors/zapi/collector/zapi.go:280]: no, I uncommented because it might help to understand other issues in the future

File: cmd/collectors/zapi/collector/zapi.go [hunk 4]
```diff
@@ -269,28 +271,28 @@ func (me *Zapi) PollData() (*matrix.Matrix, error) {
...
 
 		newpath := append(path, node.GetNameS())
-		logger.Debug(me.Prefix, " > %s(%s)%s <%s%d%s> name=[%s%s%s%s] value=[%s%s%s]", color.Grey, newpath, color.End, color.Red, len(node.GetChildren()), color.End, color.Bold, color.Cyan, node.GetNameS(), color.End, color.Yellow, node.GetContentS(), color.End)
+		key := strings.Join(newpath, ".")
+		logger.Debug(me.Prefix, " > %s(%s)%s <%s%d%s> name=[%s%s%s%s] value=[%s%s%s]", color.Grey, key, color.End, color.Red, len(node.GetChildren()), color.End, color.Bold, color.Cyan, node.GetNameS(), color.End, color.Yellow, node.GetContentS(), color.End)
 
 		if value := node.GetContentS(); value != "" {
-			key := strings.Join(newpath, ".")
-			if metric := me.Matrix.GetMetric(key); metric != nil {
+			if label, has := me.instanceLabelPaths[key]; has {
```
Comment (rahulguptajss) [inline cmd/collectors/zapi/collector/zapi.go:278]: instead of "has".. may be "exists" sounds better

File: cmd/collectors/zapi/collector/zapi.go (hunk 1 above)
Comment (vgratian) [reply cmd/collectors/zapi/collector/zapi.go:287]: > Can you add a unit test that demonstrates the problem and shows this fixes it? Especially since we plan on revisiting this

it's a bit hard, since the incoming data is from `pkg/api/ontapi/zapi`, I think we should add a method to simulate data, but this will require more time I am afraid

File: cmd/collectors/zapi/collector/zapi.go (hunk 4 above)
Comment (vgratian) [reply cmd/collectors/zapi/collector/zapi.go:278]: ok!

Comment (cgrinds) [reply cmd/collectors/zapi/collector/zapi.go:278]: I would stick with `has` that's Go's way

File: cmd/collectors/zapi/collector/zapi.go (hunk 1 above)
Comment (vgratian) [reply cmd/collectors/zapi/collector/zapi.go:287]: what I could do is add a test for parsing the counter tree from the template, that would require less time and code changes

Comment (cgrinds) [reply cmd/collectors/zapi/collector/zapi.go:287]: The change you made was to the `PollData` method and how it uses `instanceLabelPaths`. Can you create a test that creates a simple matrix, creates a Zapi struct, calls the `PollData` method with the matrix, then checks the relevant data after the call to `PollData`?

This method makes a zapi call - if that was refactored to a separate method seems like the relevant change around `instanceLabelPaths` could be made.

Comment (vgratian) [reply cmd/collectors/zapi/collector/zapi.go:287]: The problem is the ZAPI call, this will fail in the test since the test unit (and the `PollData` method) will not be able to connect to ZAPI

Comment (cgrinds) [reply cmd/collectors/zapi/collector/zapi.go:287]: That's why I was suggesting refactoring the zapi call into another method.

**Review by cgrinds — APPROVED** [review]

**Review by cgrinds — APPROVED** [review]

**Review by rahulguptajss — APPROVED** [review]
